[package]
name = "bls2brs"
version = "0.1.0"
authors = ["ns <portification@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1"
regex = "1"
bl_save = "0.2"

[dependencies.brs]
git = "https://github.com/brickadia/brs"
rev = "a95cadd7002817cf7a857dad00408b3955cfd9fb"